[package]
name = "mwallpapers"
version = "0.0.0"
workspace = ".."
edition = "2021"


[dependencies]
more-wallpapers = { path = "../more-wallpapers" }
clap = { version = "3.1", features = ["derive"] }
