[package]
name = "more-wallpapers"
version = "0.0.0"
workspace = ".."
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
educe = "0.4"
rand = { version = "0.8.5", features = ["alloc"] }
wallpaper = "3.2"
xrandr = "0.1"
