[package]
name = "setmw"
version = "0.0.0"
workspace = ".."
edition = "2021"


[dependencies]
anyhow = "1.0"
more-wallpapers = { path = "../more-wallpapers", features = ["fallback"] }
clap = { version = "3.1", features = ["derive"] }
