name: Rust

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install xrandr
        run: sudo apt-get update && sudo apt-get install -y libxrandr-dev
      - run: cargo test --workspace --all-features
      - run: cargo test --workspace
        env:
          RUST_BACKTRACE: 1

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --workspace --all-features
        env:
          RUST_BACKTRACE: 1

  macos:
    runs-on:  macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --workspace --all-features
        env:
          RUST_BACKTRACE: 1

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
      
  doc2readme:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/msrd0/cargo-doc2readme:nightly
    steps:
    - uses: actions/checkout@v3
    - run: apk add --no-cache libxrandr-dev
    - run: cargo doc2readme --check --expand-macros --manifest-path more-wallpapers/Cargo.toml
